name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install and run consul
      run: sudo apt-get -y install consul && sudo systemctl start consul
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
