name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest-alpine

    steps:
    - uses: actions/checkout@v2
    - name: Install consul
      run: apk add --update --no-cache consul
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: "consul agent -dev & crystal spec"
